### ISSUE TITLE
同步时报错

### ISSUE THREAD

**Issue by Cat9528** [sy-records/volcengine-imagex-wordpress#2]
设置好后点击同步，第一次会同步过去过去几个文件，然后大概10几秒吧就报错了，如下图，在点同步就不会有文件同步过去了，同样会报错
![QQ截图20210823162048](https://user-images.githubusercontent.com/49507090/130415121-01e02a66-141c-42fb-8ac1-c1cff1d8c8a2.png)

**Comment by Cat9528** [comment]
> 设置好后点击同步，第一次会同步过去过去几个文件，然后大概10几秒吧就报错了，如下图，在点同步就不会有文件同步过去了，同样会报错
> ![QQ截图20210823162048](https://user-images.githubusercontent.com/49507090/130415121-01e02a66-141c-42fb-8ac1-c1cff1d8c8a2.png)

**Comment by sy-records** [comment]
fpm容易执行超时，可以使用相关的工具在命令行上传
