### ISSUE TITLE
报错依然存在

### ISSUE THREAD

**Issue by Leonhzz** [sy-records/volcengine-imagex-wordpress#4]
您好，

从文章上传图片依然携带了图片处理模板参数，导致图片无法正常显示。v1.0.4

另外就是版本号外面和里面不对

= . =

**Comment by sy-records** [comment]
开启插件并上传图片，在后台媒体库和文章中不能正常访问，但在前台显示正常
请前往火山引擎官网，ImageX图片服务的服务管理中打开源地址访问功能。

**Comment by Leonhzz** [comment]
后台可以正常显示，但是前台不能，
调试前台后，发现，图片后面携带了图片处理模板参数-image结尾。删除处理参数后正常

**Comment by sy-records** [comment]
地址发来看看吧

**Comment by Leonhzz** [comment]
> 地址发来看看吧

发现问题出在图片处理配置的填写上，需要使用.image结尾的。
